version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db

    ports:
      - '5433:5433'
    volumes:
      - db:/var/lib/posgressql

volumes:
  db:
